server:
  port: ":9090"

storage:
  uploadPath: "uploads"

scp:
  remoteHost: "192.168.35.12"
  remotePort: "2222"
  username: "root"
  remotePath: "/root/"

database:
  project: "FileSystem"
  username: "root"
  password: "dutran3802"
  dbName: "FileDatabase"
  Host: "127.0.0.1:3306"

jwt:
  secretKey: "u5cSFPfL4qttU29QZpSv2lMgUZjR3dIAPpUfPxMVNrM"
  time: 24
  
